<a href="https://colab.research.google.com/github/rupasridesai/ML_23AG1A66E2/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
list1=[2,4,6,8]
array1=np.array(list1)
print(array1)

[2 4 6 8]


In [ ]:
array1 = np.array([2, 4, 6, 8])
print(array1)

[2 4 6 8]


In [ ]:
array2 = np.array([[3, 1, 4, 5],
                  [2, 6, 8, 6]])
print(array2)

[[3 1 4 5]
 [2 6 8 6]]


In [ ]:
array3 = np.array([[[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]],

                [[13, 14, 15, 16],
                 [17, 18, 19, 20],
                 [21, 22, 23, 24]]])
print(array3)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [ ]:
array4 = np.array([5,7,8])
print(array4.dtype)

int64


In [ ]:
print(array3.ndim)

3


In [10]:
print(array4.size)

3


In [11]:
array1 = np.array([[1, 2, 3],
                [6, 7, 8]])

print(array1.shape)

(2, 3)


In [12]:
array1 = np.array([6, 7, 8, 10, 13])
array2 = np.array([6, 7, 8, 10, 13], dtype=np.int32)
print(array1.itemsize)
print(array2.itemsize)


8
4


In [13]:
array1 = np.array([6, 7, 8])
array2 = np.array([[1, 2, 3],
                  [6, 7, 8]])
print("\nData of array1 is: ",array1.data)
print("Data of array2 is: ",array2.data)


Data of array1 is:  <memory at 0x7b38aec56bc0>
Data of array2 is:  <memory at 0x7b38aead9f20>


In [14]:

array1 = np.array([1, 3, 5, 7, 9])

print(array1[0])
print(array1[2])
print(array1[4])


1
5
9


In [15]:
array1[1]=10
print(array1)


[ 1 10  5  7  9]


In [16]:
array1 = np.array([[1, 3, 5, 7],
                       [9, 11, 13, 15],
                       [2, 4, 6, 8]])
element1 = array1[1, 3]  # returns 15
print("4th Element at 2nd Row:",element1)
element2 = array1[0, 1]  # returns 3
print("2nd Element at First Row:",element2)

4th Element at 2nd Row: 15
2nd Element at First Row: 3


In [17]:
array1 = np.array([1, 2, 3, 4, 5])


median = np.median(array1)

print(median)

3.0


In [18]:
marks = np.array([76, 78, 81, 66, 85])


mean_marks = np.mean(marks)

print(mean_marks)

77.2


In [19]:
marks = np.array([76, 78, 81, 66, 85])


std_marks = np.std(marks)
print(std_marks)

6.368673331236263


In [20]:
marks = np.array([76, 78, 81, 66, 85])
std_marks = np.min(marks)
print(std_marks)

66


In [21]:
marks = np.array([76, 78, 81, 66, 85])
std_marks = np.max(marks)
print(std_marks)

85
